# transform.yml
name: NBA Data Transform

on:
  workflow_run:
    workflows: ["NBA Data Ingestion"]   # name must match exactly
    types:
      - completed

jobs:
  transform:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Sync dependencies
        run: pip-sync requirements.txt

      - name: Run transform
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python src/transform.py